apiVersion: federation.symphony/v1
kind: Catalog
metadata:
  name: site-k8s-target-v1
spec: 
  version: v1
  rootResource: site-k8s-target
  type: target
  properties:
    metadata: 
      name: sitetarget:v1
    spec:
      properties:
        group: site
      topologies:
      - bindings:        
        - role: yaml.k8s
          provider: providers.target.kubectl
          config:
            inCluster: "true"
        - role: instance
          provider: providers.target.k8s
          config:
            inCluster: "true"   
            deploymentStrategy: "services"